"""add_multi_tenancy_tables

Revision ID: 0cbc3eed9c98
Revises: fd26fa5da1cc
Create Date: 2026-01-15 15:18:46.802701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cbc3eed9c98'
down_revision: Union[str, Sequence[str], None] = 'fd26fa5da1cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('tenant_members',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'user_id')
    )
    op.add_column('analytics', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'analytics', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('audit_logs', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'audit_logs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('database_connections', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'database_connections', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('knowledge_bases', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'knowledge_bases', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('llm_configurations', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'llm_configurations', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('mcp_connections', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'mcp_connections', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('projects', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'projects', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'tenant_id')
    op.drop_constraint(None, 'mcp_connections', type_='foreignkey')
    op.drop_column('mcp_connections', 'tenant_id')
    op.drop_constraint(None, 'llm_configurations', type_='foreignkey')
    op.drop_column('llm_configurations', 'tenant_id')
    op.drop_constraint(None, 'knowledge_bases', type_='foreignkey')
    op.drop_column('knowledge_bases', 'tenant_id')
    op.drop_constraint(None, 'database_connections', type_='foreignkey')
    op.drop_column('database_connections', 'tenant_id')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'tenant_id')
    op.drop_constraint(None, 'analytics', type_='foreignkey')
    op.drop_column('analytics', 'tenant_id')
    op.drop_table('tenant_members')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
