"""add_resource_access_table

Revision ID: 146b5ebff5c6
Revises: 0cbc3eed9c98
Create Date: 2026-01-15 16:20:43.110050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '146b5ebff5c6'
down_revision: Union[str, Sequence[str], None] = '0cbc3eed9c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_access',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('tenant_role', sa.String(), nullable=True),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_access_resource_id'), 'resource_access', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_access_resource_type'), 'resource_access', ['resource_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_access_resource_type'), table_name='resource_access')
    op.drop_index(op.f('ix_resource_access_resource_id'), table_name='resource_access')
    op.drop_table('resource_access')
    # ### end Alembic commands ###
