"""Add protocol to MCPConnection

Revision ID: 236f82dfa5be
Revises: e173c7a3dc74
Create Date: 2026-01-06 15:32:04.874661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '236f82dfa5be'
down_revision: Union[str, Sequence[str], None] = 'e173c7a3dc74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_connections', sa.Column('protocol', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_connections', 'protocol')
    # ### end Alembic commands ###
