"""Add system_prompt and first_message

Revision ID: 3a62c878bb11
Revises: 1ac427fc0b4b
Create Date: 2025-12-06 12:29:08.376921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a62c878bb11'
down_revision: Union[str, Sequence[str], None] = '1ac427fc0b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('agent_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('chat_sessions_project_id_fkey'), 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'projects', ['agent_id'], ['id'])
    op.drop_column('chat_sessions', 'project_id')
    op.add_column('project_members', sa.Column('agent_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('project_members_project_id_fkey'), 'project_members', type_='foreignkey')
    op.create_foreign_key(None, 'project_members', 'projects', ['agent_id'], ['id'])
    op.drop_column('project_members', 'project_id')
    op.add_column('projects', sa.Column('system_prompt', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('first_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'first_message')
    op.drop_column('projects', 'system_prompt')
    op.add_column('project_members', sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.create_foreign_key(op.f('project_members_project_id_fkey'), 'project_members', 'projects', ['project_id'], ['id'])
    op.drop_column('project_members', 'agent_id')
    op.add_column('chat_sessions', sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('chat_sessions_project_id_fkey'), 'chat_sessions', 'projects', ['project_id'], ['id'])
    op.drop_column('chat_sessions', 'agent_id')
    # ### end Alembic commands ###
