"""Add provider column to llm_configurations

Revision ID: b62339da4745
Revises: add_agent_audit_logs
Create Date: 2026-01-06 14:08:19.211471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b62339da4745'
down_revision: Union[str, Sequence[str], None] = 'add_agent_audit_logs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agent_database_connections_db_connection_id_fkey'), 'agent_database_connections', type_='foreignkey')
    op.create_foreign_key(None, 'agent_database_connections', 'database_connections', ['db_connection_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('agent_knowledge_bases_kb_id_fkey'), 'agent_knowledge_bases', type_='foreignkey')
    op.create_foreign_key(None, 'agent_knowledge_bases', 'knowledge_bases', ['kb_id'], ['id'], ondelete='CASCADE')
    op.add_column('llm_configurations', sa.Column('provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_configurations', 'provider')
    op.drop_constraint(None, 'agent_knowledge_bases', type_='foreignkey')
    op.create_foreign_key(op.f('agent_knowledge_bases_kb_id_fkey'), 'agent_knowledge_bases', 'knowledge_bases', ['kb_id'], ['id'])
    op.drop_constraint(None, 'agent_database_connections', type_='foreignkey')
    op.create_foreign_key(op.f('agent_database_connections_db_connection_id_fkey'), 'agent_database_connections', 'database_connections', ['db_connection_id'], ['id'])
    # ### end Alembic commands ###
