"""add_protocol_to_mcp_connection

Revision ID: e173c7a3dc74
Revises: dfd43eaa649e
Create Date: 2026-01-06 15:13:21.458545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e173c7a3dc74'
down_revision: Union[str, Sequence[str], None] = 'dfd43eaa649e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
