"""implement_rbac_schema

Revision ID: e8df8f621267
Revises: 57e7440ef5e7
Create Date: 2026-01-26 09:42:26.539945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8df8f621267'
down_revision: Union[str, Sequence[str], None] = '57e7440ef5e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('tenant_roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('permission_slug', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['permission_slug'], ['permissions.slug'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['tenant_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_slug')
    )
    op.add_column('tenant_groups', sa.Column('role_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'tenant_groups', 'tenant_roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.add_column('tenant_members', sa.Column('role_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'tenant_members', 'tenant_roles', ['role_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenant_members', type_='foreignkey')
    op.drop_column('tenant_members', 'role_id')
    op.drop_constraint(None, 'tenant_groups', type_='foreignkey')
    op.drop_column('tenant_groups', 'role_id')
    op.drop_table('role_permissions')
    op.drop_table('tenant_roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
