"""Add user_id to ChatSession

Revision ID: e9aaa70eda28
Revises: e8df8f621267
Create Date: 2026-01-26 12:39:14.272603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9aaa70eda28'
down_revision: Union[str, Sequence[str], None] = 'e8df8f621267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('chat_sessions', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'chat_sessions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'tenant_id')
    op.drop_column('chat_sessions', 'user_id')
    # ### end Alembic commands ###
