"""Add agent_mcp_connections

Revision ID: fd26fa5da1cc
Revises: 236f82dfa5be
Create Date: 2026-01-06 15:49:26.865653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd26fa5da1cc'
down_revision: Union[str, Sequence[str], None] = '236f82dfa5be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_mcp_connections',
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('mcp_connection_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mcp_connection_id'], ['mcp_connections.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_mcp_connections')
    # ### end Alembic commands ###
